before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: fgSGIL0ji1jBnuGgA0dNKGypC4AlPPBEQveeGgGBWr8thgrnhxF2gNmv2rYVpWzJhArYIcdZeRXoZTcNoc6QNKiT1aYLWTsAx/dNRe2+a9i1+DrLlMA1snP6484gJlbvbPiHL/jbTTRR0guj0PgTpS5chXp7qoYL3Rwj4+/40JhCjSKXuOtDBkzXwIag6XXJeaWWuKlTYU/30ms2iWWSXDZokieZZ1w/Ad2TP3CRBGPdYFuIUwOmrAl46L4N9YzliGZCz6j/ATV7olZHkchgqHg6aCOrFDwboaXWA4JrlvCg+J0G8SmXPKjyA+xH95/GQM7XZS65fjTgcNuAlX2z64Ge/I1Txr0ewjT8s9d9IzwyjCCDt+2oVE9dzV6igFyStCrlWbBUxnPeePhc0xu87S3OftqdyD+RD9d8Uw+lGO4aqxuwRMjtcxNxJ1urpdt+48GGdWOneq7VTvSXbxn325a10GusyHDdllVTp/VBgLteXIJMpzDaLgqjMwL8XJK9T3cMuAqDy2nOIOJ3keUMYyIWY9119JGFs+TLPS0vG4InKYohYoBAC9frsPpIXwSM8Wx2/aP/ABSg3XOw+ltc+PZFdzFS3lnXA79Ccq8XzMOVsPYiHAQC3WQCMffsG3SftNmOLEwNDYGezODxvGVlBhDhdmS0ASpiZ6IAu2T9lZU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
